import { useEffect, useLayoutEffect, useRef, useState } from 'react'
import { AlertTriangle, ArrowDown, Loader2, RotateCw } from 'lucide-react'
import { useLiveTurn, useThreadStore, type ThreadMessage } from '~/store/threadStore'
import { loadOlderMessages } from '~/lib/threadApi'
import { ChatBubble, HQ_MARK } from './ChatBubble'
import { LiveTurnView } from './LiveTurnView'
import { StreamErrorBoundary } from './StreamErrorBoundary'
import { useStickToBottom } from './useStickToBottom'
import { isMcpLocked } from './mcpLock'

// Start fetching the previous page a little before the very top is reached.
const LOAD_OLDER_MARGIN = '400px 0px 0px 0px'

/** A message the server has saved, so it can be edited or regenerated by id. */
export const isSaved = (m: ThreadMessage) => !m.messageId.startsWith('local-') && !m.messageId.startsWith('streamed-')

interface Props {
  threadId: string | null
  messages: ThreadMessage[]
  /** Bumped on every send, so the view jumps to the newest message. */
  followSignal: number
  onEdit: (message: ThreadMessage) => void
  onRegenerate: () => void
}

/** The scrolling message history: older pages on demand, the live reply, and a jump-to-latest button. */
export function MessageList({ threadId, messages, followSignal, onEdit, onRegenerate }: Props) {
  const liveTurn = useLiveTurn(threadId)
  const olderAvailable = useThreadStore((s) => (threadId ? s.olderAvailable[threadId] ?? false : false))
  const scrollRef = useRef<HTMLDivElement>(null)
  const contentRef = useRef<HTMLDivElement>(null)
  const sentinelRef = useRef<HTMLDivElement>(null)
  const activity = `${messages.length}:${liveTurn?.content.length ?? 0}:${liveTurn?.toolSteps.length ?? 0}`
  const { atBottom, hasUnseen, scrollToBottom } = useStickToBottom(scrollRef, contentRef, threadId, activity)
  const olderPage = useOlderPages(threadId, olderAvailable, scrollRef, sentinelRef, messages[0]?.messageId)

  useEffect(() => {
    if (followSignal > 0) scrollToBottom()
  }, [followSignal, scrollToBottom])

  const last = messages[messages.length - 1]
  // Regenerating after a session update would replace that update, which is the drive log.
  // A saved question with no reply and nothing running: the reply failed, or was stopped before it wrote anything.
  const lastLocked = isMcpLocked(messages, messages.length - 1)
  const unanswered = !liveTurn && last?.role === 'user' && isSaved(last) && !lastLocked
  const canRegenerate = !liveTurn && last?.role === 'assistant' && isSaved(last) && !last.driver && !lastLocked

  return (
    <div className="flex-1 min-h-0 relative">
      <div ref={scrollRef} className="absolute inset-0 overflow-y-auto overscroll-contain p-3 sm:p-6">
        <div ref={contentRef} className="max-w-4xl mx-auto space-y-3">
          <div ref={sentinelRef} />
          {olderAvailable && (
            <div className="flex justify-center py-1">
              <button
                type="button"
                onClick={() => void olderPage.load()}
                disabled={olderPage.loading}
                className="flex items-center gap-1.5 h-9 px-3 rounded-full border border-white/10 text-xs text-neutral-400 hover:text-white hover:bg-white/5 disabled:opacity-60"
              >
                {olderPage.loading && <Loader2 className="w-3.5 h-3.5 animate-spin" />}
                {olderPage.loading ? 'Loading earlier messages' : 'Load earlier messages'}
              </button>
            </div>
          )}

          {messages.length === 0 && !liveTurn && (
            <div className="flex flex-col items-center justify-center h-full text-center text-neutral-500 py-12">
              <img src={HQ_MARK} alt="" className="w-12 h-12 object-contain mb-3 opacity-60" />
              <p className="text-sm">{threadId ? 'Start a conversation' : 'Type a message or command to begin'}</p>
            </div>
          )}

          {messages.map((m, i) => (
            <StreamErrorBoundary key={m.messageId} plainText={m.content} resetKey={m.content}>
            <ChatBubble
              key={m.messageId}
              message={{
                id: m.messageId,
                role: m.role,
                content: m.content,
                timestamp: m.createdAt,
                toolSteps: m.toolSteps,
                stepCredits: m.stepCredits,
                reasoning: m.reasoning,
                attachments: m.attachments,
                stopped: m.stopped,
                driver: m.driver,
                viaMcp: m.viaMcp,
              }}
              onEdit={m.role === 'user' && !liveTurn && isSaved(m) && !isMcpLocked(messages, i) ? () => onEdit(m) : undefined}
              onRegenerate={canRegenerate && m === last ? onRegenerate : undefined}
            />
            </StreamErrorBoundary>
          ))}

          {unanswered && (
            <div role="alert" className="flex items-center gap-2 mb-4 px-3 py-2 rounded-xl border border-amber-500/30 bg-amber-500/[0.04] text-xs text-neutral-200">
              <AlertTriangle className="w-4 h-4 shrink-0 text-amber-400" />
              <span className="flex-1 min-w-0">HQ did not finish a reply to this message.</span>
              <button
                type="button"
                onClick={onRegenerate}
                className="flex items-center gap-1.5 h-9 px-3 rounded-full border border-white/15 hover:bg-white/10"
              >
                <RotateCw className="w-3.5 h-3.5" /> Retry
              </button>
            </div>
          )}

          <LiveTurnView threadId={threadId} />
        </div>
      </div>

      {!atBottom && (
        <button
          type="button"
          onClick={() => scrollToBottom(true)}
          className="absolute bottom-3 left-1/2 -translate-x-1/2 z-20 flex items-center gap-1.5 h-10 px-4 rounded-full border border-white/15 bg-neutral-900/90 backdrop-blur text-xs text-neutral-200 shadow-lg hover:bg-neutral-800"
          title="Scroll to the newest message"
        >
          <ArrowDown className="w-3.5 h-3.5" />
          {hasUnseen ? 'New messages' : 'Latest'}
          {hasUnseen && <span className="w-1.5 h-1.5 rounded-full bg-emerald-400" />}
        </button>
      )}
    </div>
  )
}

/**
 * Fetches the page before the oldest message when the top comes into view,
 * and keeps the reader's place: the new page is added above without moving
 * what is on screen. Chrome's scroll anchoring may already have held the
 * place, so the offset is only applied when the scroll position did not move.
 */
function useOlderPages(
  threadId: string | null,
  available: boolean,
  scrollRef: React.RefObject<HTMLDivElement | null>,
  sentinelRef: React.RefObject<HTMLDivElement | null>,
  firstId: string | undefined,
) {
  const [loading, setLoading] = useState(false)
  const before = useRef<{ height: number; top: number } | null>(null)

  const load = async () => {
    const el = scrollRef.current
    if (!threadId || !el || loading || !available) return
    before.current = { height: el.scrollHeight, top: el.scrollTop }
    setLoading(true)
    try {
      await loadOlderMessages(threadId)
    } catch (err) {
      console.warn('MessageList: failed to load earlier messages', err)
      before.current = null
    } finally {
      setLoading(false)
    }
  }

  useLayoutEffect(() => {
    const el = scrollRef.current
    const prev = before.current
    if (!el || !prev) return
    before.current = null
    if (el.scrollTop === prev.top) el.scrollTop = prev.top + (el.scrollHeight - prev.height)
  }, [firstId, scrollRef])

  useEffect(() => {
    const root = scrollRef.current
    const target = sentinelRef.current
    if (!root || !target || !available) return
    const observer = new IntersectionObserver(
      (entries) => {
        if (entries.some((e) => e.isIntersecting)) void load()
      },
      { root, rootMargin: LOAD_OLDER_MARGIN },
    )
    observer.observe(target)
    return () => observer.disconnect()
  }, [available, threadId, loading, scrollRef, sentinelRef])

  return { load, loading }
}
