/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VaultRouteImport } from './routes/vault'
import { Route as UsageRouteImport } from './routes/usage'
import { Route as TasksRouteImport } from './routes/tasks'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SessionsRouteImport } from './routes/sessions'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VaultIndexRouteImport } from './routes/vault/index'
import { Route as VaultSplatRouteImport } from './routes/vault/$'

const VaultRoute = VaultRouteImport.update({
  id: '/vault',
  path: '/vault',
  getParentRoute: () => rootRouteImport,
} as any)
const UsageRoute = UsageRouteImport.update({
  id: '/usage',
  path: '/usage',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsRoute = SessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VaultIndexRoute = VaultIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => VaultRoute,
} as any)
const VaultSplatRoute = VaultSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => VaultRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/notifications': typeof NotificationsRoute
  '/sessions': typeof SessionsRoute
  '/settings': typeof SettingsRoute
  '/setup': typeof SetupRoute
  '/tasks': typeof TasksRoute
  '/usage': typeof UsageRoute
  '/vault': typeof VaultRouteWithChildren
  '/vault/$': typeof VaultSplatRoute
  '/vault/': typeof VaultIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/notifications': typeof NotificationsRoute
  '/sessions': typeof SessionsRoute
  '/settings': typeof SettingsRoute
  '/setup': typeof SetupRoute
  '/tasks': typeof TasksRoute
  '/usage': typeof UsageRoute
  '/vault/$': typeof VaultSplatRoute
  '/vault': typeof VaultIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/notifications': typeof NotificationsRoute
  '/sessions': typeof SessionsRoute
  '/settings': typeof SettingsRoute
  '/setup': typeof SetupRoute
  '/tasks': typeof TasksRoute
  '/usage': typeof UsageRoute
  '/vault': typeof VaultRouteWithChildren
  '/vault/$': typeof VaultSplatRoute
  '/vault/': typeof VaultIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/chat'
    | '/notifications'
    | '/sessions'
    | '/settings'
    | '/setup'
    | '/tasks'
    | '/usage'
    | '/vault'
    | '/vault/$'
    | '/vault/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/chat'
    | '/notifications'
    | '/sessions'
    | '/settings'
    | '/setup'
    | '/tasks'
    | '/usage'
    | '/vault/$'
    | '/vault'
  id:
    | '__root__'
    | '/'
    | '/chat'
    | '/notifications'
    | '/sessions'
    | '/settings'
    | '/setup'
    | '/tasks'
    | '/usage'
    | '/vault'
    | '/vault/$'
    | '/vault/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChatRoute: typeof ChatRoute
  NotificationsRoute: typeof NotificationsRoute
  SessionsRoute: typeof SessionsRoute
  SettingsRoute: typeof SettingsRoute
  SetupRoute: typeof SetupRoute
  TasksRoute: typeof TasksRoute
  UsageRoute: typeof UsageRoute
  VaultRoute: typeof VaultRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vault': {
      id: '/vault'
      path: '/vault'
      fullPath: '/vault'
      preLoaderRoute: typeof VaultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/usage': {
      id: '/usage'
      path: '/usage'
      fullPath: '/usage'
      preLoaderRoute: typeof UsageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions': {
      id: '/sessions'
      path: '/sessions'
      fullPath: '/sessions'
      preLoaderRoute: typeof SessionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vault/': {
      id: '/vault/'
      path: '/'
      fullPath: '/vault/'
      preLoaderRoute: typeof VaultIndexRouteImport
      parentRoute: typeof VaultRoute
    }
    '/vault/$': {
      id: '/vault/$'
      path: '/$'
      fullPath: '/vault/$'
      preLoaderRoute: typeof VaultSplatRouteImport
      parentRoute: typeof VaultRoute
    }
  }
}

interface VaultRouteChildren {
  VaultSplatRoute: typeof VaultSplatRoute
  VaultIndexRoute: typeof VaultIndexRoute
}

const VaultRouteChildren: VaultRouteChildren = {
  VaultSplatRoute: VaultSplatRoute,
  VaultIndexRoute: VaultIndexRoute,
}

const VaultRouteWithChildren = VaultRoute._addFileChildren(VaultRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChatRoute: ChatRoute,
  NotificationsRoute: NotificationsRoute,
  SessionsRoute: SessionsRoute,
  SettingsRoute: SettingsRoute,
  SetupRoute: SetupRoute,
  TasksRoute: TasksRoute,
  UsageRoute: UsageRoute,
  VaultRoute: VaultRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
