[package]
name = "hq-vault"
version.workspace = true
edition.workspace = true

[dependencies]
hq-core = { workspace = true }
serde = { workspace = true }
serde_yaml = { workspace = true }
anyhow = { workspace = true }
tracing = { workspace = true }
chrono = { workspace = true }
gray_matter = { workspace = true }
tempfile = "3"
