# Created for submission to microsoft/winget-pkgs; validate with: winget validate --manifest <dir>
PackageIdentifier: HQ.Lite
PackageVersion: 0.9.1-main.136
DefaultLocale: en-US
ManifestType: version
ManifestVersion: 1.6.0
